server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
logging:
  level:
    root: info