-- liquibase formatted sql

-- changeset argus:1711269682930-1
CREATE TABLE calendar
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    year     INTEGER                                 NOT NULL,
    holidays JSONB,
    CONSTRAINT pk_calendar PRIMARY KEY (id)
);

